Refactor actions to methods in pre-push

diff --git a/hooks/pre-push b/hooks/pre-push
--- a/hooks/pre-push
+++ b/hooks/pre-push
@@ -1,76 +1,60 @@
-#!/bin/sh
+#!/usr/bin/env bash
 
-# An example hook script to verify what is about to be pushed.  Called by "git
-# push" after it has checked the remote status, but before anything has been
-# pushed.  If this script exits with a non-zero status nothing will be pushed.
-#
-# This hook is called with the following parameters:
-#
-# $1 -- Name of the remote to which the push is being done
-# $2 -- URL to which the push is being done
-#
-# If pushing without using a named remote those arguments will be equal.
-#
-# Information about the commits which are being pushed is supplied as lines to
-# the standard input in the form:
-#
-#   <local ref> <local sha1> <remote ref> <remote sha1>
-#
-# This sample shows how to prevent push of commits where the log message starts
-# with "WIP" (work in progress).
+check_for_wip_commit() {
+	while read local_ref local_sha remote_ref remote_sha
+	do
+		if [ "$local_sha" = $z40 ]
+		then
+			# Handle delete
+			:
+		else
+			if [ "$remote_sha" = $z40 ]
+			then
+				# New branch, examine all commits
+				range="$local_sha"
+			else
+				# Update to existing branch, examine new commits
+				range="$remote_sha..$local_sha"
+			fi
+
+			# Check for WIP commit
+			commit=`git rev-list -n 1 --grep '^WIP' "$range"`
+			if [ -n "$commit" ]
+			then
+				echo >&2 "Found WIP commit in $local_ref, not pushing"
+				exit 1
+			fi
+		fi
+	done
+}
+
+pull() {
+	echo "Performing git pull --rebase"
+	git pull --rebase
+
+	if [ $? -ne 0 ]
+	then
+	  echo "Rebase failure, Cannot push to $remote" >&2
+	  exit 1
+	fi
+}
+
+run_tests() {
+	echo "Running tests"
+	./gradlew clean build
+
+	if [ $? -ne 0 ]
+	then
+		echo "Tests failed, Cannot push to $remote" >&2
+	  exit 1
+	fi
+}
 
 remote="$1"
 url="$2"
 
 z40=0000000000000000000000000000000000000000
 
-while read local_ref local_sha remote_ref remote_sha
-do
-	if [ "$local_sha" = $z40 ]
-	then
-		# Handle delete
-		:
-	else
-		if [ "$remote_sha" = $z40 ]
-		then
-			# New branch, examine all commits
-			range="$local_sha"
-		else
-			# Update to existing branch, examine new commits
-			range="$remote_sha..$local_sha"
-		fi
-
-		# Check for WIP commit
-		commit=`git rev-list -n 1 --grep '^WIP' "$range"`
-		if [ -n "$commit" ]
-		then
-			echo >&2 "Found WIP commit in $local_ref, not pushing"
-			exit 1
-		fi
-	fi
-done
-
-echo "Not a WIP command"
-echo "Performing git pull --rebase"
-
-git pull --rebase
-
-if [ $? -eq 0 ]
-then
-    echo "Rebased Successfully"
-    echo "Running Tests"
-
-    ./gradlew clean test
-
-    if [ $? -eq 0 ]
-    then
-        echo "Tested Successfully, Pushing to $remote"
-        exit 0
-    else
-       echo "Test Failure, Cannot push to $remote" >&2
-	   exit 1
-    fi
-else
-  echo "Rebase failure, Cannot push to $remote" >&2
-  exit 1
-fi
+check_for_wip_commit \
+&& pull \
+&& run_tests \
