Format error messages in red in pre-push hook

diff --git a/hooks/pre-push b/hooks/pre-push
--- a/hooks/pre-push
+++ b/hooks/pre-push
@@ -22,7 +22,7 @@ check_for_wip_commit() {
 			local commit=`git rev-list -n 1 --grep 'WIP' "$range"`
 			if [ -n "$commit" ]
 			then
-				echo >&2 "Found WIP commit in $local_ref, not pushing"
+				echo >&2 "$(tput setaf 1)Found WIP commit in $local_ref, not pushing$(tput sgr 0)"
 				exit 1
 			fi
 		fi
@@ -36,7 +36,7 @@ check_for_unTracked_files() {
 
     if [ -n "$unTrackedFiles" ]
 	then
-		tput setaf 1; echo >&2 "Found Untracked files(s):"
+		echo >&2 "$(tput setaf 1)Found Untracked files(s):$(tput sgr 0)"
 		echo >&2 "$unTrackedFiles"
 		echo >&2 "Commit or Stash file(s) before pushing to $remote"
 		exit 1
@@ -50,7 +50,7 @@ pull() {
 
 	if [ $? -ne 0 ]
 	then
-	  echo "Rebase failure, Cannot push to $remote" >&2
+	  echo "$(tput setaf 1)Rebase failure, Cannot push to $remote$(tput sgr 0)" >&2
 	  exit 1
 	fi
 }
@@ -61,7 +61,7 @@ run_tests() {
 
 	if [ $? -ne 0 ]
 	then
-		echo "Tests failed, Cannot push to $remote" >&2
+		echo "$(tput setaf 1)Tests failed, Cannot push to $remote$(tput sgr 0)" >&2
 	  exit 1
 	fi
 }
